source 'https://rubygems.org'

gem 'rails', '3.2.11'

gem 'pg'
gem 'thin'

# I18n
gem 'rails-i18n'
gem 'devise-i18n'

# Authentication
#gem 'devise', '~> 2.1.2'
#gem 'omniauth', '~> 1.1.0'
#gem 'omniauth-facebook', '~> 1.2.0'
#gem 'omniauth-twitter', '~> 0.0.12'

# Administration
#gem 'activeadmin'

# Tools
gem 'inherited_resources'
gem 'simple_form'
#gem 'has_scope'

# Views
gem 'jquery-rails'
gem 'slim'
gem 'slim-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'less-rails'
  gem 'twitter-bootstrap-rails'
  gem 'therubyracer', platform: :ruby
end

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'shoulda-matchers'
  gem 'machinist', '~> 2.0'
  gem 'database_cleaner'
  gem 'capybara'
end

group :test do
  gem 'simplecov', require: false
end
